### ISSUE TITLE
Upgrade to react 16 dependency

### ISSUE THREAD

**Issue by sshadmand** [wbinnssmith/react-user-avatar#11]
When building against latest React, warning are beginning to pop up. I suggest getting ahead of it.

`warning "react-user-avatar@1.9.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".`

**Comment by richardvenneman** [comment]
I opened a pull request for this: https://github.com/wbinnssmith/react-user-avatar/pull/10

**Comment by agmansi970** [comment]
@swrobel
